FROM centos:7

MAINTAINER piece

RUN yum -y update

RUN yum -y upgrade

RUN yum install -y epel-release vim wget libaio libaio-devel npm

RUN yum -y install ack telnet git

# RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

WORKDIR /root

CMD ["tail", "-f", "/dev/null"]