version: '3.9'

services:
    workstation:
        build:
            context: ./
        container_name: workstation
        hostname: workstation
        volumes:
            # 設定時區與本機時區相同
            - /etc/localtime:/etc/localtime:ro
            - .:/root/workstation
            - ~/.gitconfig:/root/.gitconfig:ro
            - ~/.ssh:/root/.ssh:ro